version: '3'

services:
  db:
    image: mongo
    container_name: db
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    links:
      - db
    ports:
      - '4650:8081'
    depends_on:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=r00t
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    links:
      - db
    ports:
      - '4690:5000'
    volumes:
      - ./api/src:/usr/src/app/src
      - ./api/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    links:
      - api
    ports:
      - '4660:80'
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
